apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-envvar
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka-envtest
        image: bhuvidockerhub/kafkaproject:v4.0
        env:
        - name: TOPIC_NAME
          value: "new-pizza-orders"
        - name: NO_OF_MESSAGES
          value: "25"
        - name: MAX_WAIT_TIME
          value: "2"
        - name: NO_OF_TOPICS
          value: "3"
        - name: PARTITIONS_PER_TOPIC
          value: "3"
        - name: REPLICAS_PER_PARTITIONS
          value: "3"
        ports:
        imagePullPolicy: Always 
        args: ["multi_topic_producer1.py", "bash"]
        #args: ["pizzaapp_multiconsumer1.py", "bash"]
      imagePullSecrets:
      - name: regcred
