apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-dockerprod
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka-producer
        image: bhuvidockerhub/kafkaproject:v3.0
        ports:
        imagePullPolicy: Always 
        args: ["multi_topic_producer1.py", "bash"]
      imagePullSecrets:
      - name: regcred
