apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: my-cruise-control-rebalance
  labels:
    strimzi.io/cluster: my-cluster-with-metrics
# no goals specified, using the default goals from the Cruise Control configuration
spec: {}
