#Code resused from Official Strimzi repo - https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/cruise-control/kafka-rebalance.yaml
#Changes made as per the requirement 
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: my-cruise-control-rebalance
  labels:
    strimzi.io/cluster: my-cluster-metrics
# no goals specified, using the default goals from the Cruise Control configuration
spec: {}
