apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: my-cruise-control-rebalance-half
  labels:
    strimzi.io/cluster: my-cluster-metrics
spec:
  concurrentPartitionMovementsPerBroker: 2 
  concurrentIntraBrokerPartitionMovements: 1 
  concurrentLeaderMovements: 500 
