apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: my-cruise-control-rebalance-double
  labels:
    strimzi.io/cluster: my-cluster-metrics
spec:
  concurrentPartitionMovementsPerBroker: 10
  concurrentIntraBrokerPartitionMovements: 4
  concurrentLeaderMovements: 1200 
